### ISSUE TITLE
Sample not available at plnkr.co

### ISSUE THREAD

**Issue by ameya** [infusion-code/angular-maps#70]
All the sample code have been taken down from plnkr.co resulting on links ending up on not found page.

**Comment by thor-schueler** [comment]
Hmm, the plunks still seems to be there, but they are all failing with a 503 access control header error from unpkg.com: 

Failed to load https://unpkg.com/angular-maps/dist/index.js:No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://run.plnkr.co' is therefore not allowed access. The response had HTTP status code 503.

unpkg.com must have changed their policies or something. I'll look into it over the next few days to see whether I can resolve this somehow....

**Comment by thor-schueler** [comment]
This should be resolved now. The issue was that plunkr is going through an upgrade and the url formats have changed. I updated the urls. The issue with the 503s from unpkg.com is sporadic. sometimes I have to refresh to plunk 2 or 3 times to get it to work.... 

@ameya: could you please confirm the samples. I keep the issue open for a few days just in case...

**Comment by METACEO** [comment]
@ameya - it's not a small endeavor, but we're considering moving our examples from [plnkr](https://next.plnkr.co/) to [stackblitz](https://stackblitz.com/) (considering stackblitz is powered by Visual Studio Code and me and @thor-schueler's company is tight with MS, it also makes sense!) I've already got an angular 4 environment consuming an ng6-built `angular-maps` [here](https://stackblitz.com/edit/angular4-nha6fc) - a lot of the code was copied and pasted over, so regarding all of our examples, it'll be plenty of easy migrations to make it a time consumer (well worth it, though!)

**Comment by thor-schueler** [comment]
I added the stackblitz sample to the samples page as 'experimental'. I think as we release 6.0, we'll move all the samples over to stackblitz...

**Comment by jmsunseri** [comment]
I'm still getting a 404 error when trying to view the plunks.  would it be possible to add the sample source code to the repo?

**Comment by thor-schueler** [comment]
Can you please paste the urls that you get in the browser?

**Comment by jmsunseri** [comment]
Trying to view the Bing 20,000 unclustered example and i get this plunker

http://plnkr.co/plunk/bb8wu5



Sincerely

Justin Sunseri
Please don't print this e-mail unless you really need to.

**Comment by thor-schueler** [comment]
Ah yes, change the url to http://next.plnkr.co/plunk/bb8wu5. 

Unfortunately, plunker is doing internal redirection depending on whether you are on the traditional or the new and the url format has changed between the two. 

Alternatively you can change to the new version in the plunkr blue bar across the top...

Let me know whether this works.

**Comment by thor-schueler** [comment]
All samples have been moved to Stackblitz due to some plunkr stability issues...
